class SecurityApprovalSteps:
    SECURITY_CLASSIFIED = "SECURITY_CLASSIFIED"
    SUBJECT_TO_ITAR_CONTROLS = "SUBJECT_TO_ITAR_CONTROLS"
    F1686_DETAILS = "F1686_DETAILS"
    F680_REFERENCE_NUMBER = "F680_REFERENCE_NUMBER"
    SECURITY_OTHER_DETAILS = "SECURITY_OTHER_DETAILS"
