class FormSteps:
    ENTITY_TYPE = "ENTITY_TYPE"
    END_USER_NAME = "END_USER_NAME"
    END_USER_ADDRESS = "END_USER_ADDRESS"
    SECURITY_GRADING = "SECURITY_GRADING"
    INTENDED_END_USE = "INTENDED_END_USE"
