from exporter.applications.views.goods.common import constants


class AddGoodPlatformSteps:
    NAME = constants.NAME
    PRODUCT_CONTROL_LIST_ENTRY = constants.PRODUCT_CONTROL_LIST_ENTRY
    PV_GRADING = constants.PV_GRADING
    PV_GRADING_DETAILS = constants.PV_GRADING_DETAILS
    PRODUCT_USES_INFORMATION_SECURITY = constants.PRODUCT_USES_INFORMATION_SECURITY
    PRODUCT_DOCUMENT_AVAILABILITY = constants.PRODUCT_DOCUMENT_AVAILABILITY
    PRODUCT_DOCUMENT_SENSITIVITY = constants.PRODUCT_DOCUMENT_SENSITIVITY
    PRODUCT_DOCUMENT_UPLOAD = constants.PRODUCT_DOCUMENT_UPLOAD
    PRODUCT_MILITARY_USE = "PRODUCT_MILITARY_USE"
