case_selectors = {
    "header": "#heading-reference-code",
    "make_recommendation": "#main-content > div > a",
    "approve_all": "#id_recommendation_1",
    "continue": "#submit-id-submit",
    "belgium_checkbox": "#id_countries_0",
    "ukraine_checkbox": "#id_countries_1",
    "fcdo_approval_reason": "#id_approval_reasons",
    "recommendation_review": "#main-content",
    "cases_form": "#form-cases",
    "assigned_queues": "#assigned-queues",
    "counter_sign_details": ".govuk-details__text",
    "counter_sign_approval_reason": "#id_form-0-approval_reasons",
    "counter_sign_reason": "div.govuk-grid-column-three-quarters > p.govuk-body",
    "fcdo_reason": "div.govuk-grid-row > div.govuk-cookie-banner__content",
}
