exclude: (exporter/assets/built/|caseworker/assets/built/)
default_language_version:
  python: python3.9
repos:
  # ruff-pre-commit docs recommend running ruff before black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      # Config for ruff lives in pyproject.toml
      - id: ruff
        args: [ --fix ]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
      # Config for black lives in pyproject.toml
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==24.3.0]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
  - repo: https://github.com/uktrade/pii-secret-check-hooks
    rev: 0.0.0.36
    hooks:
      - id: pii_secret_filename
        files: ""
        language: python
        args: [exclude]
        pass_filenames: true
        require_serial: true
      - id: pii_secret_file_content
        files: ""
        language: python
        args: [--exclude=pii-secret-exclude.txt]
        pass_filenames: true
        require_serial: true
        additional_dependencies: [click==8.0.4]
      #- id: hooks_version_check
      #  name: Checking local hooks against latest release
      #  verbose: true
      #  require_serial: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        files: "^(core|caseworker|exporter)/assets/javascripts"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.13.0'
    hooks:
      - id: eslint
        files: "^(core|caseworker|exporter)/assets/javascripts"
        additional_dependencies:
          - eslint@8.44.0 # /PS-IGNORE
          - eslint-plugin-jest@27.2.3 # /PS-IGNORE
