version: '3.2'

services:
  caseworker:
    depends_on:
      - redis
      - api
    build:
      context: .
      dockerfile: Dockerfile.e2e
    environment:
      # Below values can be found in vault
      DIRECTORY_SSO_API_CLIENT_BASE_URL: ${DIRECTORY_SSO_API_CLIENT_BASE_URL}
      DIRECTORY_SSO_API_CLIENT_API_KEY: ${DIRECTORY_SSO_API_CLIENT_API_KEY}
      AUTHBROKER_CLIENT_ID: ${AUTHBROKER_CLIENT_ID}
      AUTHBROKER_CLIENT_SECRET: ${AUTHBROKER_CLIENT_SECRET}
      TEST_SSO_NAME: ${TEST_SSO_NAME}
      EXPORTER_TEST_SSO_EMAIL: ${EXPORTER_TEST_SSO_EMAIL}
      EXPORTER_TEST_SSO_PASSWORD: ${EXPORTER_TEST_SSO_PASSWORD}
      TEST_SSO_EMAIL: ${TEST_SSO_EMAIL}
      TEST_SSO_PASSWORD: ${TEST_SSO_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
    env_file:
      - ./caseworker.env
    ports:
      - 8200:8200
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      dockerize -wait tcp://api:8100 -timeout 5m
      npm install
      npm run build_caseworker
      python manage.py runserver 0.0.0.0:${PORT:-8200}
    stdin_open: true
    tty: true
