FROM gcr.io/sre-docker-registry/lite-frontend-dependencies:latest

WORKDIR /app

# Use pyenv to install python packages
ADD Pipfile* /app/
RUN pipenv install --dev --system --deploy

ADD package.json .
ADD package-lock.json .

# Build application
RUN npm install

# Add application directory to image
ADD . /app
