version: '3.2'

services:
  caseworker:
    depends_on:
      - redis
      - api
    build:
      context: .
      dockerfile: Dockerfile.e2e
    environment:
      # Below values can be found in vault
      AUTHBROKER_CLIENT_ID: ${AUTHBROKER_CLIENT_ID}
      AUTHBROKER_CLIENT_SECRET: ${AUTHBROKER_CLIENT_SECRET}
      EXPORTER_TEST_SSO_EMAIL: ${EXPORTER_TEST_SSO_EMAIL}
      TEST_SSO_EMAIL: ${TEST_SSO_EMAIL}
    env_file:
      - ./caseworker.env
    ports:
      - 8200:8200
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      dockerize -wait tcp://api:8100 -timeout 5m
      npm install
      npm run build_caseworker
      python manage.py runserver 0.0.0.0:${PORT:-8200}
    stdin_open: true
    tty: true
