# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.ruff.lint]
select = ["F401", "S", "G", "LOG"]

[tool.ruff.lint.per-file-ignores]
"./{unit_tests,ui_tests,tests_common}/*" = ["S101", "S311", "S108", "S314"]
"*/tests/*" = ["S101"]
"./lite_forms/tests.py" = ["S101"]
