from django.urls import path

from .views import (
    add,
    edit,
    summary,
)


urlpatterns = [
    path("add-new/", add.AddGoodComponentAccessory.as_view(), name="new_good_component_accessory"),
    path(
        "<uuid:good_pk>/add-to-application/",
        add.AddGoodComponentAccessoryToApplication.as_view(),
        name="new_good_component_accessory_to_application",
    ),
    path(
        "<uuid:good_pk>/attach/",
        add.AddGoodComponentAccessoryToApplication.as_view(),
        name="attach_component_accessory_to_application",
    ),
    path(
        "<uuid:good_pk>/product-summary/",
        summary.ComponentAccessoryProductSummary.as_view(),
        name="component_accessory_product_summary",
    ),
    path(
        "<uuid:good_on_application_pk>/product-on-application-summary/",
        summary.ComponentAccessoryProductOnApplicationSummary.as_view(),
        name="component_accessory_on_application_summary",
    ),
    path("<uuid:good_pk>/edit/name/", edit.ComponentAccessoryEditName.as_view(), name="component_accessory_edit_name"),
    path(
        "<uuid:good_pk>/edit/component-accessory-details/",
        edit.ComponentAccessoryEditComponentDetails.as_view(),
        name="component_accessory_edit_component_details",
    ),
    path(
        "<uuid:good_pk>/edit/control-list-entries/",
        edit.ComponentAccessoryEditControlListEntry.as_view(),
        name="component_accessory_edit_control_list_entries",
    ),
    path(
        "<uuid:good_pk>/edit/pv-grading/",
        edit.ComponentAccessoryEditPVGrading.as_view(),
        name="component_accessory_edit_pv_grading",
    ),
    path(
        "<uuid:good_pk>/edit/pv-grading-details/",
        edit.ComponentAccessoryEditPVGradingDetails.as_view(),
        name="component_accessory_edit_pv_grading_details",
    ),
    path(
        "<uuid:good_pk>/edit/uses-information-security/",
        edit.ComponentAccessoryEditUsesInformationSecurity.as_view(),
        name="component_accessory_edit_uses_information_security",
    ),
    path(
        "<uuid:good_pk>/edit/product-document-availability/",
        edit.ComponentAccessoryEditProductDocumentAvailability.as_view(),
        name="component_accessory_edit_product_document_availability",
    ),
    path(
        "<uuid:good_pk>/edit/product-document-sensitivity/",
        edit.ComponentAccessoryEditProductDocumentSensitivity.as_view(),
        name="component_accessory_edit_product_document_sensitivity",
    ),
    path(
        "<uuid:good_pk>/edit/product-document/",
        edit.ComponentAccessoryEditProductDocumentView.as_view(),
        name="component_accessory_edit_product_document",
    ),
    path(
        "<uuid:good_pk>/edit/product-description/",
        edit.ComponentAccessoryEditProductDescriptionView.as_view(),
        name="component_accessory_edit_product_description",
    ),
    path(
        "<uuid:good_pk>/edit/part-number/",
        edit.ComponentAccessoryEditPartNumberView.as_view(),
        name="component_accessory_edit_part_number",
    ),
    path(
        "<uuid:good_pk>/edit/military-use/",
        edit.ComponentAccessoryEditMilitaryUseView.as_view(),
        name="component_accessory_edit_military_use",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-exported/",
        edit.ComponentAccessoryOnApplicationSummaryEditOnwardExported.as_view(),
        name="component_accessory_on_application_summary_edit_onward_exported",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-altered/",
        edit.ComponentAccessoryOnApplicationSummaryEditOnwardAltered.as_view(),
        name="component_accessory_on_application_summary_edit_onward_altered",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-incorporated/",
        edit.ComponentAccessoryOnApplicationSummaryEditOnwardIncorporated.as_view(),
        name="component_accessory_on_application_summary_edit_onward_incorporated",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/quantity-value/",
        edit.ComponentAccessoryOnApplicationSummaryEditQuantityValue.as_view(),
        name="component_accessory_on_application_summary_edit_quantity_value",
    ),
]
