from django.urls import path

from .views import (
    add,
    edit,
    summary,
)


urlpatterns = [
    path("add-new/", add.AddGoodCompleteItem.as_view(), name="new_good_complete_item"),
    path(
        "<uuid:good_pk>/add-to-application/",
        add.AddGoodCompleteItemToApplication.as_view(),
        name="new_good_complete_item_to_application",
    ),
    path(
        "<uuid:good_pk>/attach/",
        add.AddGoodCompleteItemToApplication.as_view(),
        name="attach_complete_item_to_application",
    ),
    path(
        "<uuid:good_pk>/product-summary/",
        summary.CompleteItemProductSummary.as_view(),
        name="complete_item_product_summary",
    ),
    path(
        "<uuid:good_on_application_pk>/product-on-application-summary/",
        summary.CompleteItemProductOnApplicationSummary.as_view(),
        name="complete_item_on_application_summary",
    ),
    path("<uuid:good_pk>/edit/name/", edit.CompleteItemEditName.as_view(), name="complete_item_edit_name"),
    path(
        "<uuid:good_pk>/edit/control-list-entries/",
        edit.CompleteItemEditControlListEntry.as_view(),
        name="complete_item_edit_control_list_entries",
    ),
    path(
        "<uuid:good_pk>/edit/pv-grading/",
        edit.CompleteItemEditPVGrading.as_view(),
        name="complete_item_edit_pv_grading",
    ),
    path(
        "<uuid:good_pk>/edit/pv-grading-details/",
        edit.CompleteItemEditPVGradingDetails.as_view(),
        name="complete_item_edit_pv_grading_details",
    ),
    path(
        "<uuid:good_pk>/edit/uses-information-security/",
        edit.CompleteItemEditUsesInformationSecurity.as_view(),
        name="complete_item_edit_uses_information_security",
    ),
    path(
        "<uuid:good_pk>/edit/product-document-availability/",
        edit.CompleteItemEditProductDocumentAvailability.as_view(),
        name="complete_item_edit_product_document_availability",
    ),
    path(
        "<uuid:good_pk>/edit/product-document-sensitivity/",
        edit.CompleteItemEditProductDocumentSensitivity.as_view(),
        name="complete_item_edit_product_document_sensitivity",
    ),
    path(
        "<uuid:good_pk>/edit/product-document/",
        edit.CompleteItemEditProductDocumentView.as_view(),
        name="complete_item_edit_product_document",
    ),
    path(
        "<uuid:good_pk>/edit/product-description/",
        edit.CompleteItemEditProductDescriptionView.as_view(),
        name="complete_item_edit_product_description",
    ),
    path(
        "<uuid:good_pk>/edit/part-number/",
        edit.CompleteItemEditPartNumberView.as_view(),
        name="complete_item_edit_part_number",
    ),
    path(
        "<uuid:good_pk>/edit/military-use/",
        edit.CompleteItemEditMilitaryUseView.as_view(),
        name="complete_item_edit_military_use",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-exported/",
        edit.CompleteItemOnApplicationSummaryEditOnwardExported.as_view(),
        name="complete_item_on_application_summary_edit_onward_exported",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-altered/",
        edit.CompleteItemOnApplicationSummaryEditOnwardAltered.as_view(),
        name="complete_item_on_application_summary_edit_onward_altered",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-incorporated/",
        edit.CompleteItemOnApplicationSummaryEditOnwardIncorporated.as_view(),
        name="complete_item_on_application_summary_edit_onward_incorporated",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/quantity-value/",
        edit.CompleteItemOnApplicationSummaryEditQuantityValue.as_view(),
        name="complete_item_on_application_summary_edit_quantity_value",
    ),
]
