import math

from enum import Enum

DATE_FORMAT = "%d %B %Y"
ALL_CASES_QUEUE_ID = "00000000-0000-0000-0000-000000000001"
UPDATED_CASES_QUEUE_ID = "00000000-0000-0000-0000-000000000004"

ENFORCEMENT_XML_MAX_FILE_SIZE = 1 << 20  # 1 MB

SLA_RADIUS = 16
SLA_DIAMETER = SLA_RADIUS * 2
SLA_CIRCUMFERENCE = SLA_DIAMETER * math.pi


class GoodSystemFlags:
    CLC_FLAG = "00000000-0000-0000-0000-000000000002"
    PV_GRADING_FLAG = "00000000-0000-0000-0000-000000000003"


# Permissions
MAKE_FINAL_DECISIONS = "MAKE_FINAL_DECISIONS"
DECISIONS_LIST = ["approve", "refuse", "no_licence_required"]

# Role IDs
SUPER_USER_ROLE_ID = "00000000-0000-0000-0000-000000000002"

# Document types
GENERATED_DOCUMENT = "GENERATED"

# Case types
APPLICATION_CASE_TYPES = ["open", "standard", "hmrc"]
CLEARANCE_CASE_TYPES = ["exhibition_clearance", "gifting_clearance", "f680_clearance"]


class AdviceType:
    CONFLICTING = "conflicting"


class Permission(Enum):
    MANAGE_TEAM_ADVICE = "MANAGE_TEAM_ADVICE"
    MANAGE_TEAM_CONFIRM_OWN_ADVICE = "MANAGE_TEAM_CONFIRM_OWN_ADVICE"
    MANAGE_LICENCE_FINAL_ADVICE = "MANAGE_LICENCE_FINAL_ADVICE"
    MANAGE_CLEARANCE_FINAL_ADVICE = "MANAGE_CLEARANCE_FINAL_ADVICE"
    ADMINISTER_ROLES = "ADMINISTER_ROLES"
    REVIEW_GOODS = "REVIEW_GOODS"
    CONFIGURE_TEMPLATES = "CONFIGURE_TEMPLATES"
    MANAGE_LICENCE_DURATION = "MANAGE_LICENCE_DURATION"
    RESPOND_PV_GRADING = "RESPOND_PV_GRADING"
    MANAGE_ORGANISATIONS = "MANAGE_ORGANISATIONS"
    REOPEN_CLOSED_CASES = "REOPEN_CLOSED_CASES"
    MANAGE_FLAGGING_RULES = "MANAGE_FLAGGING_RULES"
    MANAGE_TEAM_ROUTING_RULES = "MANAGE_TEAM_ROUTING_RULES"
    MANAGE_ALL_ROUTING_RULES = "MANAGE_ALL_ROUTING_RULES"
    ACTIVATE_FLAGS = "ACTIVATE_FLAGS"
    MANAGE_PICKLISTS = "MANAGE_PICKLISTS"
    ENFORCEMENT_CHECK = "ENFORCEMENT_CHECK"
    MAINTAIN_FOOTNOTES = "MAINTAIN_FOOTNOTES"
    MAINTAIN_OGL = "MAINTAIN_OGL"
    REMOVE_AUTHORISED_COUNTERSINGER_FLAGS = "REMOVE_AUTHORISED_COUNTERSINGER_FLAGS"
    REMOVE_HEAD_OF_LICENSING_UNIT_FLAGS = "REMOVE_HEAD_OF_LICENSING_UNIT_FLAGS"


class FlagLevels:
    CASES = "cases"
    GOODS = "goods"
    ORGANISATIONS = "organisations"
    DESTINATIONS = "destinations"
    PARTY_ON_APPLICATION = "party_on_application"


class UserStatuses:
    ACTIVE = "Active"
    DEACTIVATED = "Deactivated"


class SystemTeamsID(Enum):
    ADMIN = "00000000-0000-0000-0000-000000000001"


class CaseType:
    EXHIBITION = "exhibition_clearance"
    F680 = "f680_clearance"
    HMRC = "hmrc"
