import groovy.json.JsonSlurper
import groovy.json.JsonOutput


def triggerBuild(branch, environment, token) {
    def body = JsonOutput.toJson([
        branch: branch,
        parameters: [run_ui_tests: "true", run_unit_tests: "false", environment: environment]
    ])
    def response = httpRequest (
        consoleLogResponseBody: false,
        contentType: 'APPLICATION_JSON',
        circleToken: token,
        acceptType: 'APPLICATION_JSON',
        httpMode: 'POST',
        requestBody: body,
        url: "https://circleci.com/api/v2/project/gh/uktrade/lite-frontend/pipeline")
    if (response.status >= 300){
        throw new Exception("ERROR: triggerBuild() failed")
    }
    def json = new JsonSlurper().parseText(response.content)
    return [json.status, json.number]
}

def getBuildStatus( number, token )
{
    def response = httpRequest (
        consoleLogResponseBody: false,
        circleToken: token,
        acceptType: 'APPLICATION_JSON',
        url: "https://circleci.com/api/v2/project/gh/uktrade/lite-frontend/job/$number")
    if (response.status >= 300){
        throw new Exception("ERROR: getBuildStatus() failed")
    }
    def json = new JsonSlurper().parseText(response.content)
    return [json.status, json.number]
}

def waitForBuildStatusToChange(number, current_status, wait_states, poll_delay, msg, token){
    println " ... $msg"
    while(status in wait_states){
        sleep(poll_delay)
        (status, number) = getBuildStatus( number, token)
    }
    return status
}

pipeline {

    parameters {
        choice(name: 'ENVIRONMENT', description: 'choose what environment to run in', choices: 'dev\nqa\ndevpopcorn\ndevkoala\nsandbox\nstaging\nuat\ndevdata')
        string(name: 'BRANCH', defaultValue: 'master', description: 'choose branch to run against')
        string(name: 'CIRCLE_API_TOKEN')
    }

    agent any

    stages {
        stage('trigger build') {
            steps{
                script{
                    def token = params.CIRCLE_API_TOKEN
                    def request_poll_delay = CCI_POLL_DELAY
                    println "trigger CircleCi tests job for $project/$branch"

                    (status, number) = triggerBuild( "run_the_tests", params.BRANCH, params.ENVIRONMENT , token)
                    println "Kicked off CircleCi build https://circleci.com/gh/uktrade/lite-cci-e2e/$number"

                    status = waitForBuildStatusToChange( number, status, ['queued', 'not_running'], request_poll_delay, "waiting for job to start", token)

                    status = waitForBuildStatusToChange( number, status, ['running'], request_poll_delay, "waiting for job to finish", token)

                    println "Final status = $status"
                    currentBuild.result = status in ['success','fixed']? 'SUCCESS': 'FAILURE'
                }
            }
        }
    }
}