class FormSteps:
    APPLICATION_NAME = "APPLICATION_NAME"
    HAS_MADE_PREVIOUS_APPLICATION = "HAS_MADE_PREVIOUS_APPLICATION"
    EXCEPTIONAL_CIRCUMSTANCES = "EXCEPTIONAL_CIRCUMSTANCES"
    EXCEPTIONAL_CIRCUMSTANCES_REASONS = "EXCEPTIONAL_CIRCUMSTANCES_REASONS"
    PREVIOUS_APPLICATION = "PREVIOUS_APPLICATION"
