from django.urls import path

from .views import (
    add,
    attach,
    edit,
    summary,
)


urlpatterns = [
    path("add-new/", add.AddGoodFirearm.as_view(), name="new_good_firearm"),
    path(
        "<uuid:good_pk>/add-to-application/",
        add.AddGoodFirearmToApplication.as_view(),
        name="new_good_firearm_to_application",
    ),
    path(
        "<uuid:good_pk>/attach/",
        attach.AttachFirearmToApplication.as_view(),
        name="attach_firearm_to_application",
    ),
    path(
        "<uuid:good_pk>/product-summary/",
        summary.FirearmProductSummary.as_view(),
        name="firearm_product_summary",
    ),
    path(
        "<uuid:good_on_application_pk>/product-on-application-summary/",
        summary.FirearmProductOnApplicationSummary.as_view(),
        name="product_on_application_summary",
    ),
    path(
        "<uuid:good_on_application_pk>/attach-product-on-application-summary/",
        summary.FirearmAttachProductOnApplicationSummary.as_view(),
        name="attach_product_on_application_summary",
    ),
    path(
        "<uuid:good_pk>/edit/category/",
        edit.FirearmEditCategory.as_view(),
        name="firearm_edit_category",
    ),
    path("<uuid:good_pk>/edit/name/", edit.FirearmEditName.as_view(), name="firearm_edit_name"),
    path(
        "<uuid:good_pk>/edit/control-list-entries/",
        edit.FirearmEditControlListEntry.as_view(),
        name="firearm_edit_control_list_entries",
    ),
    path(
        "<uuid:good_pk>/edit/calibre/",
        edit.FirearmEditCalibre.as_view(),
        name="firearm_edit_calibre",
    ),
    path(
        "<uuid:good_pk>/edit/replica/",
        edit.FirearmEditReplica.as_view(),
        name="firearm_edit_replica",
    ),
    path(
        "<uuid:good_pk>/edit/pv-grading/",
        edit.FirearmEditPVGrading.as_view(),
        name="firearm_edit_pv_grading",
    ),
    path(
        "<uuid:good_pk>/edit/pv-grading-details/",
        edit.FirearmEditPVGradingDetails.as_view(),
        name="firearm_edit_pv_grading_details",
    ),
    path(
        "<uuid:good_pk>/edit/product-document-availability/",
        edit.FirearmEditProductDocumentAvailability.as_view(),
        name="firearm_edit_product_document_availability",
    ),
    path(
        "<uuid:good_pk>/edit/product-document-sensitivity/",
        edit.FirearmEditProductDocumentSensitivity.as_view(),
        name="firearm_edit_product_document_sensitivity",
    ),
    path(
        "<uuid:good_pk>/edit/product-document/",
        edit.FirearmEditProductDocumentView.as_view(),
        name="firearm_edit_product_document",
    ),
    path(
        "<uuid:good_pk>/edit/product-description/",
        edit.FirearmEditProductDescriptionView.as_view(),
        name="firearm_edit_product_description",
    ),
    path(
        "<uuid:good_pk>/edit/registered-firearms-dealer/",
        edit.FirearmEditRegisteredFirearmsDealer.as_view(),
        name="firearm_edit_registered_firearms_dealer",
    ),
    path(
        "<uuid:good_pk>/edit/section-5-firearms-act-1968/",
        edit.FirearmEditSection5FirearmsAct1968.as_view(),
        name="firearm_edit_section_5_firearms_act_1968",
    ),
    path(
        "<uuid:good_pk>/edit/letter-of-authority/",
        edit.FirearmEditLetterOfAuthority.as_view(),
        name="firearm_edit_letter_of_authority",
    ),
    path(
        "<uuid:good_pk>/edit/firearms-act-1968/",
        edit.FirearmEditFirearmsAct1968.as_view(),
        name="firearm_edit_firearms_act_1968",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/firearm-certificate/",
        edit.FirearmProductOnApplicationSummaryEditFirearmCertificate.as_view(),
        name="product_on_application_summary_edit_firearm_certificate",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/shotgun-certificate/",
        edit.FirearmProductOnApplicationSummaryEditShotgunCertificate.as_view(),
        name="product_on_application_summary_edit_shotgun_certificate",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/made-before-1938/",
        edit.FirearmProductOnApplicationSummaryEditMadeBefore1938.as_view(),
        name="product_on_application_summary_edit_made_before_1938",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/year-of-manufacture/",
        edit.FirearmProductOnApplicationSummaryEditYearOfManufacture.as_view(),
        name="product_on_application_summary_edit_year_of_manufacture",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-exported/",
        edit.FirearmProductOnApplicationSummaryEditOnwardExported.as_view(),
        name="product_on_application_summary_edit_onward_exported",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-altered/",
        edit.FirearmProductOnApplicationSummaryEditOnwardAltered.as_view(),
        name="product_on_application_summary_edit_onward_altered",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-incorporated/",
        edit.FirearmProductOnApplicationSummaryEditOnwardIncorporated.as_view(),
        name="product_on_application_summary_edit_onward_incorporated",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/is-deactivated/",
        edit.FirearmProductOnApplicationSummaryEditIsDeactivated.as_view(),
        name="product_on_application_summary_edit_is_deactivated",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/is-deactivated-to-standard/",
        edit.FirearmProductOnApplicationSummaryEditIsDeactivatedToStandard.as_view(),
        name="product_on_application_summary_edit_is_deactivated_to_standard",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/quantity-value/",
        edit.FirearmProductOnApplicationSummaryEditQuantityValue.as_view(),
        name="product_on_application_summary_edit_quantity_value",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/serial-identification-markings/",
        edit.FirearmProductOnApplicationSummaryEditSerialIdentificationMarkings.as_view(),
        name="product_on_application_summary_edit_serial_identification_markings",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/serial-numbers/",
        edit.FirearmProductOnApplicationSummaryEditSerialNumbers.as_view(),
        name="product_on_application_summary_edit_serial_numbers",
    ),
]
