from django.urls import path

from .views import (
    add,
    edit,
    summary,
)


urlpatterns = [
    path("add-new/", add.AddGoodTechnology.as_view(), name="new_good_technology"),
    path(
        "<uuid:good_pk>/add-to-application/",
        add.AddGoodTechnologyToApplication.as_view(),
        name="new_good_technology_to_application",
    ),
    path(
        "<uuid:good_pk>/attach/",
        add.AddGoodTechnologyToApplication.as_view(),
        name="attach_technology_to_application",
    ),
    path(
        "<uuid:good_pk>/product-summary/",
        summary.TechnologyProductSummary.as_view(),
        name="technology_product_summary",
    ),
    path(
        "<uuid:good_on_application_pk>/product-on-application-summary/",
        summary.TechnologyProductOnApplicationSummary.as_view(),
        name="technology_on_application_summary",
    ),
    path("<uuid:good_pk>/edit/name/", edit.TechnologyEditName.as_view(), name="technology_edit_name"),
    path(
        "<uuid:good_pk>/edit/control-list-entries/",
        edit.TechnologyEditControlListEntry.as_view(),
        name="technology_edit_control_list_entries",
    ),
    path(
        "<uuid:good_pk>/edit/pv-grading/",
        edit.TechnologyEditPVGrading.as_view(),
        name="technology_edit_pv_grading",
    ),
    path(
        "<uuid:good_pk>/edit/pv-grading-details/",
        edit.TechnologyEditPVGradingDetails.as_view(),
        name="technology_edit_pv_grading_details",
    ),
    path(
        "<uuid:good_pk>/edit/security-features/",
        edit.TechnologyEditSecurityFeatures.as_view(),
        name="technology_edit_security_features",
    ),
    path(
        "<uuid:good_pk>/edit/declared-at-customs/",
        edit.TechnologyEditDeclaredAtCustoms.as_view(),
        name="technology_edit_declared_at_customs",
    ),
    path(
        "<uuid:good_pk>/edit/product-document-availability/",
        edit.TechnologyEditProductDocumentAvailability.as_view(),
        name="technology_edit_product_document_availability",
    ),
    path(
        "<uuid:good_pk>/edit/product-document-sensitivity/",
        edit.TechnologyEditProductDocumentSensitivity.as_view(),
        name="technology_edit_product_document_sensitivity",
    ),
    path(
        "<uuid:good_pk>/edit/product-document/",
        edit.TechnologyEditProductDocumentView.as_view(),
        name="technology_edit_product_document",
    ),
    path(
        "<uuid:good_pk>/edit/product-description/",
        edit.TechnologyEditProductDescriptionView.as_view(),
        name="technology_edit_product_description",
    ),
    path(
        "<uuid:good_pk>/edit/part-number/",
        edit.TechnologyEditPartNumberView.as_view(),
        name="technology_edit_part_number",
    ),
    path(
        "<uuid:good_pk>/edit/military-use/",
        edit.TechnologyEditMilitaryUseView.as_view(),
        name="technology_edit_military_use",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-exported/",
        edit.TechnologyOnApplicationSummaryEditOnwardExported.as_view(),
        name="technology_on_application_summary_edit_onward_exported",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-altered/",
        edit.TechnologyOnApplicationSummaryEditOnwardAltered.as_view(),
        name="technology_on_application_summary_edit_onward_altered",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/onward-incorporated/",
        edit.TechnologyOnApplicationSummaryEditOnwardIncorporated.as_view(),
        name="technology_on_application_summary_edit_onward_incorporated",
    ),
    path(
        "<uuid:good_on_application_pk>/<str:summary_type>/edit/quantity-value/",
        edit.TechnologyOnApplicationSummaryEditQuantityValue.as_view(),
        name="technology_on_application_summary_edit_quantity_value",
    ),
]
