from exporter.applications.views.goods.common import constants


class AddGoodMaterialSteps:
    NAME = constants.NAME
    PRODUCT_CONTROL_LIST_ENTRY = constants.PRODUCT_CONTROL_LIST_ENTRY
    PV_GRADING = constants.PV_GRADING
    PV_GRADING_DETAILS = constants.PV_GRADING_DETAILS
    PRODUCT_DOCUMENT_AVAILABILITY = constants.PRODUCT_DOCUMENT_AVAILABILITY
    PRODUCT_DESCRIPTION = constants.PRODUCT_DESCRIPTION
    PRODUCT_DOCUMENT_SENSITIVITY = constants.PRODUCT_DOCUMENT_SENSITIVITY
    PRODUCT_DOCUMENT_UPLOAD = constants.PRODUCT_DOCUMENT_UPLOAD
    PRODUCT_MILITARY_USE = "PRODUCT_MILITARY_USE"
    PART_NUMBER = constants.PART_NUMBER


class AddGoodMaterialToApplicationSteps:
    ONWARD_EXPORTED = constants.ONWARD_EXPORTED
    ONWARD_ALTERED_PROCESSED = constants.ONWARD_ALTERED_PROCESSED
    ONWARD_INCORPORATED = constants.ONWARD_INCORPORATED
    UNIT_QUANTITY_AND_VALUE = "UNIT_QUANTITY_AND_VALUE"
