class ApplicationFormSteps:
    APPLICATION_NAME = "APPLICATION_NAME"
    PREVIOUS_APPLICATION = "PREVIOUS_APPLICATION"


class ProductFormSteps:
    NAME_AND_DESCRIPTION = "NAME_AND_DESCRIPTION"


class EndUserFormSteps:
    END_USER_NAME = "END_USER_NAME"


class ConsigneeFormSteps:
    CONSIGNEE_NAME = "CONSIGNEE_NAME"
