@all
Feature: Add a HMRC query

  @a_caseworker_test
  Scenario: Send data to HMRC
    Given I sign in to SSO or am signed into SSO
    And I create an application with <name>,<product>,<clc_rating>,<end_user_name>,<end_user_address>,<consignee_name>,<consignee_address>,<country>,<end_use>
    And the status is set to "submitted"

  Examples:
  | name    | product | clc_rating  | end_user_name      | end_user_address  | country | consignee_name      | consignee_address   | end_use                  |
  | Test    | Rifle   | PL9002      | Automated End user | 1234, High street | BE      | Automated Consignee | 1234, Trade centre  | Research and devel

  @skip @regression @HMRC
  Scenario: Add a HMRC query
    Given I sign in to SSO or am signed into SSO
    And I create HMRC query
    When I go to the case list page
    Then I should see my case in the cases list
    And I should see my case SLA
    When I go to application previously created
    And I go to the documents tab
    Then I see my autogenerated application form
