class FormSteps:
    APPROVAL_TYPE = "APPROVAL_TYPE"
    PRODUCT_NAME = "PRODUCT_NAME"
    PRODUCT_DESCRIPTION = "PRODUCT_DESCRIPTION"
    FOREIGN_TECHNOLOGY_OR_INFORMATION_SHARED = "FOREIGN_TECHNOLOGY_OR_INFORMATION_SHARED"
