class FormSteps:
    PRODUCT_NAME = "PRODUCT_NAME"
    PRODUCT_DESCRIPTION = "PRODUCT_DESCRIPTION"
    FOREIGN_TECHNOLOGY_OR_INFORMATION_SHARED = "FOREIGN_TECHNOLOGY_OR_INFORMATION_SHARED"
    CONTROLLED_UNDER_ITAR = "CONTROLLED_UNDER_ITAR"
    ABOUT_CONTROLLED_UNDER_ITAR = "ABOUT_CONTROLLED_UNDER_ITAR"
